export const A = {
  IMPORT_STATE: 'IMPORT_STATE',
  SET_TITLE: 'SET_TITLE',

  ADD_SECTION: 'ADD_SECTION',
  RENAME_SECTION: 'RENAME_SECTION',
  CYCLE_SECTION_COLOR: 'CYCLE_SECTION_COLOR',
  TOGGLE_SECTION_COLLAPSE: 'TOGGLE_SECTION_COLLAPSE',
  MOVE_SECTION: 'MOVE_SECTION',
  DELETE_SECTION: 'DELETE_SECTION',
  TOGGLE_QA_COLLAPSE: 'TOGGLE_QA_COLLAPSE',

  ADD_SLIDE: 'ADD_SLIDE',
  DUPLICATE_SLIDE: 'DUPLICATE_SLIDE',
  DELETE_SLIDE: 'DELETE_SLIDE',
  MOVE_SLIDE: 'MOVE_SLIDE',
  RELOCATE_SLIDE: 'RELOCATE_SLIDE',

  SELECT_SLIDE: 'SELECT_SLIDE',
  SELECT_PAGE: 'SELECT_PAGE',
  ADD_PAGE: 'ADD_PAGE',
  DELETE_PAGE: 'DELETE_PAGE',

  UPDATE_SLIDE_NOTES: 'UPDATE_SLIDE_NOTES',
  UPDATE_SLIDE_BG: 'UPDATE_SLIDE_BG',
  UPDATE_SLIDE_BG_COLOR: 'UPDATE_SLIDE_BG_COLOR',
  UPDATE_SLIDE_NODE_ICON: 'UPDATE_SLIDE_NODE_ICON',
  UPDATE_SLIDE_NODE_LABEL: 'UPDATE_SLIDE_NODE_LABEL',

  TOGGLE_NOTES: 'TOGGLE_NOTES',

  // Scene/object actions (Presentation Studio, Milestone 1)
  SET_SELECTION: 'SET_SELECTION',
  ADD_OBJECT: 'ADD_OBJECT',
  DELETE_OBJECT: 'DELETE_OBJECT',
  DUPLICATE_OBJECT: 'DUPLICATE_OBJECT',
  UPDATE_OBJECT_TRANSFORM: 'UPDATE_OBJECT_TRANSFORM',
  UPDATE_OBJECT_DATA: 'UPDATE_OBJECT_DATA',
  REORDER_OBJECT_Z: 'REORDER_OBJECT_Z',
  DETACH_OBJECT: 'DETACH_OBJECT',

  // Multi-object actions (Presentation Studio, Milestone 2)
  UPDATE_OBJECTS_TRANSFORM: 'UPDATE_OBJECTS_TRANSFORM',
  DELETE_OBJECTS: 'DELETE_OBJECTS',
  DUPLICATE_OBJECTS: 'DUPLICATE_OBJECTS',
  GROUP_OBJECTS: 'GROUP_OBJECTS',
  UNGROUP_OBJECTS: 'UNGROUP_OBJECTS',
  ALIGN_OBJECTS: 'ALIGN_OBJECTS',
  DISTRIBUTE_OBJECTS: 'DISTRIBUTE_OBJECTS',

  // Backgrounds & theme (Presentation Studio, Milestone 4)
  UPDATE_SCENE_BACKGROUND: 'UPDATE_SCENE_BACKGROUND',
  UPDATE_SECTION_BACKGROUND: 'UPDATE_SECTION_BACKGROUND',
  UPDATE_DECK_BACKGROUND: 'UPDATE_DECK_BACKGROUND',
  UPDATE_THEME_TOKEN: 'UPDATE_THEME_TOKEN',

  // Master slides & reusable components (Presentation Studio, Milestone 5)
  ADD_MASTER_SLIDE: 'ADD_MASTER_SLIDE',
  DELETE_MASTER_SLIDE: 'DELETE_MASTER_SLIDE',
  SET_SECTION_MASTER: 'SET_SECTION_MASTER',
  SET_DECK_MASTER: 'SET_DECK_MASTER',
  ADD_COMPONENT: 'ADD_COMPONENT',
  DELETE_COMPONENT: 'DELETE_COMPONENT',
  INSERT_COMPONENT_INSTANCE: 'INSERT_COMPONENT_INSTANCE',
  CREATE_COMPONENT_FROM_SELECTION: 'CREATE_COMPONENT_FROM_SELECTION',

  // Diagram builder (Presentation Studio, Milestone 6)
  CREATE_CONNECTOR: 'CREATE_CONNECTOR',
  INSERT_DIAGRAM_TEMPLATE: 'INSERT_DIAGRAM_TEMPLATE',

  // Asset library & presentation templates (Presentation Studio, Milestone 9)
  ADD_ASSET: 'ADD_ASSET',
  DELETE_ASSET: 'DELETE_ASSET',
  ADD_SECTION_FROM_TEMPLATE: 'ADD_SECTION_FROM_TEMPLATE',

  // Editable overview graph (Presentation Studio v2, Milestone D)
  ADD_EDGE: 'ADD_EDGE',
  DELETE_EDGE: 'DELETE_EDGE',
  REDIRECT_EDGE: 'REDIRECT_EDGE',
} as const;

export type ActionType = (typeof A)[keyof typeof A];
